services:
  # DATABASES
  # User service database
  postgres5411:
    image: postgres:latest
    container_name: postgres5411
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account
    ports:
      - "5411:5432"
    networks:
      - app-network
    volumes:
      - postgres5411_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres5411_data: