spring:
  application:
    name: "transaction-service"
  datasource:
    url: "jdbc:postgresql://localhost:5451/transaction"
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
  cloud:
    function:
      definition: handleTransferDebitedEvent
    stream:
      defaultBinder: kafka
      bindings:
        # Transfer events
        handleTransferDebitedEvent-in-0:
          destination: transfer-money
          content-type: application/json
          group: transaction-service-group

        transactionCompleted-out-0:
          destination: transaction-completed-topic
          content-type: application/json
          
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8040

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}