spring:
  application:
    name: "transfer-service"
  datasource:
    url: "jdbc:postgresql://localhost:5421/transfer"
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
  cloud:
    function:
      definition: transferResponseConsumer
    stream:
      defaultBinder: kafka
      bindings:
        transfer-out-0: #bu binding mesajları transfer-money topic gönderir
          destination: transfer-money
          content-type: application/json
          group: transfer-money-group
        transferResponseConsumer-in-0: # Fonksiyon ismi + "-in-0" formatı
          destination: transfer-response # Dinlenecek topic adı
          content-type: application/json
          group: transfer-response-group



eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}